# -*- coding: utf-8 -*-
"""task5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_INK7XK-Sqs0FweU9wXwO0Yj9CQP9Mq
"""

import zipfile
import os

# Unzip dataset
zip_path = "archive (9).zip"
output_folder = "data"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(output_folder)

print("✅ Dataset unzipped successfully.")

import pandas as pd

# Load first 10,000 rows only (for faster analysis)
df = pd.read_csv("data/US_Accidents_March23.csv", nrows=10000)

df.head()

df.info()
df.isnull().sum().sort_values(ascending=False)

import matplotlib.pyplot as plt
import seaborn as sns

df['Start_Time'] = pd.to_datetime(df['Start_Time'])
df['Hour'] = df['Start_Time'].dt.hour

plt.figure(figsize=(10,5))
sns.countplot(x='Hour', data=df, palette='viridis')
plt.title("Accidents by Hour of Day")
plt.xlabel("Hour")
plt.ylabel("Number of Accidents")
plt.show()

top_states = df['State'].value_counts().nlargest(10)

plt.figure(figsize=(8,6))
sns.barplot(x=top_states.values, y=top_states.index, palette='magma')
plt.title("Top 10 States with Most Accidents")
plt.xlabel("Number of Accidents")
plt.ylabel("State")
plt.show()

top_weather = df['Weather_Condition'].value_counts().nlargest(10)

plt.figure(figsize=(10,6))
sns.barplot(x=top_weather.values, y=top_weather.index, palette='coolwarm')
plt.title("Top 10 Weather Conditions")
plt.xlabel("Number of Accidents")
plt.ylabel("Weather Condition")
plt.show()

